### PR TITLE
Suppress unnecessary errors

### PR DESCRIPTION
**Pull request by RogerSelwyn**
Relates to - https://github.com/gerard33/sony_bravia_psk/issues/22

### CODE REVIEW

**Comment by RogerSelwyn** [comment]
Thanks for your ongoing work on this.

I notice by the way that the published HA Integration 0.4.1, uses version 0.2.0 of this module, whilst it looks like you have upped the version in manifest.json, but not released it.

**Comment by gerard33** [comment]
Thanks!
Will have a look at the version of the module. The release zip shows 0.2.0 indeed, although I have upped the version to 0.2.3.

**Comment by gerard33** [comment]
Version number for the module should be now correct at 0.2.4 in release 0.4.2. of the integration.

**Comment by RogerSelwyn** [comment]
Cool

**Pull request merged**
