### PR TITLE
Add open_app API

### PR DESCRIPTION
**Pull request by rchl**
For starting arbitrary apps using their URI

### CODE REVIEW

**Comment by gerard33** [comment]
As I don't have an Android TV can you give an example how to use this in the HA custom compenent? Because this is a different approach than the [PR](https://github.com/custom-components/media_player.braviatv_psk/pull/22) you made for the custom component?

**Comment by rchl** [comment]
Yes, those are two separate features.
Code implementing this in the component is here: https://github.com/rchl/media_player.braviatv_psk/commit/7e3f84635bf14cd95751a4d80311709922afba50

I was planning to also add some way of getting all app IDs but didn't get around to doing that. That's why I've never submitted a PR.

**Comment by gerard33** [comment]
Thanks for the PR. Let me know if you want to make a PR for this in the component as well.

**Comment by rchl** [comment]
I'll have a look as soon as I have time.

**Comment by gerard33** [comment]
I am doing some tests on your PR https://github.com/custom-components/media_player.braviatv_psk/pull/22 for the services. I was able to show the description of the service in HA now. While doing that I can also add the service for this using the code you mentioned above. After that I will make a new release so it get's available in HACS.

**Comment by gerard33** [comment]
I have added this service in v0.3.3 and it's available for Android TVs.
The PR with the command_id service is also added including the descriptions in HA.

Thanks for your PRs! Your efforts and patience are much appreciated :+1:

**Pull request merged**
